"""
Task Agent Graph State

State schema for Task Agent LangGraph workflow - SQL-based approach.
"""

from typing import TypedDict, List, Dict, Any, Optional


class TaskGraphState(TypedDict):
    """State for Task Agent graph - SQL-based approach"""
    
    # Input
    query: str
    workspace_id: str
    user_id: str
    session_id: str
    
    # Database schema
    schema_info: str  # Database schema documentation
    
    # Intent & Planning
    intent: str  # 'QUERY' or 'ACTION'
    tool_calls: List[Dict[str, Any]]  # List of tool calls to execute
    tool_results: List[Dict[str, Any]]  # Results from tool execution
    
    # SQL Generation
    generated_sql: str  # SQL query generated by LLM
    sql_parameters: Dict[str, Any]  # Parameters for SQL query
    
    # SQL Execution
    sql_results: List[Dict[str, Any]]  # Results from SQL execution
    sql_success: bool  # Whether SQL executed successfully
    sql_error: Optional[str]  # Error message if SQL failed
    
    # Analysis
    insights: List[str]  # Key insights from data
    risks: List[Dict[str, Any]]  # Identified risks
    recommendations: List[str]  # Actionable recommendations
    
    # Response
    answer: str  # Final formatted answer
    confidence: float  # Confidence score
    
    # Metadata
    row_count: int  # Number of rows returned
    query_time_ms: int  # Query execution time
    metadata: Dict[str, Any]
    
    # Error handling
    error: Optional[str]


def create_initial_state(
    query: str,
    workspace_id: str,
    user_id: str = "anonymous",
    session_id: str = "default-session"
) -> TaskGraphState:
    """
    Create initial state for task analysis graph
    
    Args:
        query: User's query about tasks
        workspace_id: Workspace to analyze
        user_id: User making the query
        session_id: Session ID for conversation context
    
    Returns:
        Initial graph state
    """
    return TaskGraphState(
        # Input
        query=query,
        workspace_id=workspace_id,
        user_id=user_id,
        session_id=session_id,
        
        # Database schema (will be loaded)
        schema_info="",
        
        # SQL (will be generated)
        generated_sql="",
        sql_parameters={'workspace_id': workspace_id},
        
        # SQL execution (empty initially)
        sql_results=[],
        sql_success=False,
        sql_error=None,
        
        # Analysis results (empty initially)
        insights=[],
        risks=[],
        recommendations=[],
        
        # Response (empty initially)
        answer="",
        confidence=0.0,
        
        # Metadata
        row_count=0,
        query_time_ms=0,
        metadata={},
        error=None
    )
